package com.landasoft.excelcontactsorcl.pojo;

import java.util.Date;

public class TFileImportHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILE_IMPORT_HISTORY.ID
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILE_IMPORT_HISTORY.FILE_NAME
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILE_IMPORT_HISTORY.FILE_ROW_NUM
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    private String fileRowNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILE_IMPORT_HISTORY.FILE_IMPORT_NUM
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    private Short fileImportNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILE_IMPORT_HISTORY.FILE_ID
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILE_IMPORT_HISTORY.CATAGORY
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    private String catagory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILE_IMPORT_HISTORY.REMARK
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILE_IMPORT_HISTORY.CREATED
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILE_IMPORT_HISTORY.UPDATED
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILE_IMPORT_HISTORY.ID
     *
     * @return the value of T_FILE_IMPORT_HISTORY.ID
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILE_IMPORT_HISTORY.ID
     *
     * @param id the value for T_FILE_IMPORT_HISTORY.ID
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILE_IMPORT_HISTORY.FILE_NAME
     *
     * @return the value of T_FILE_IMPORT_HISTORY.FILE_NAME
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILE_IMPORT_HISTORY.FILE_NAME
     *
     * @param fileName the value for T_FILE_IMPORT_HISTORY.FILE_NAME
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILE_IMPORT_HISTORY.FILE_ROW_NUM
     *
     * @return the value of T_FILE_IMPORT_HISTORY.FILE_ROW_NUM
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public String getFileRowNum() {
        return fileRowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILE_IMPORT_HISTORY.FILE_ROW_NUM
     *
     * @param fileRowNum the value for T_FILE_IMPORT_HISTORY.FILE_ROW_NUM
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public void setFileRowNum(String fileRowNum) {
        this.fileRowNum = fileRowNum == null ? null : fileRowNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILE_IMPORT_HISTORY.FILE_IMPORT_NUM
     *
     * @return the value of T_FILE_IMPORT_HISTORY.FILE_IMPORT_NUM
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public Short getFileImportNum() {
        return fileImportNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILE_IMPORT_HISTORY.FILE_IMPORT_NUM
     *
     * @param fileImportNum the value for T_FILE_IMPORT_HISTORY.FILE_IMPORT_NUM
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public void setFileImportNum(Short fileImportNum) {
        this.fileImportNum = fileImportNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILE_IMPORT_HISTORY.FILE_ID
     *
     * @return the value of T_FILE_IMPORT_HISTORY.FILE_ID
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILE_IMPORT_HISTORY.FILE_ID
     *
     * @param fileId the value for T_FILE_IMPORT_HISTORY.FILE_ID
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILE_IMPORT_HISTORY.CATAGORY
     *
     * @return the value of T_FILE_IMPORT_HISTORY.CATAGORY
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public String getCatagory() {
        return catagory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILE_IMPORT_HISTORY.CATAGORY
     *
     * @param catagory the value for T_FILE_IMPORT_HISTORY.CATAGORY
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public void setCatagory(String catagory) {
        this.catagory = catagory == null ? null : catagory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILE_IMPORT_HISTORY.REMARK
     *
     * @return the value of T_FILE_IMPORT_HISTORY.REMARK
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILE_IMPORT_HISTORY.REMARK
     *
     * @param remark the value for T_FILE_IMPORT_HISTORY.REMARK
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILE_IMPORT_HISTORY.CREATED
     *
     * @return the value of T_FILE_IMPORT_HISTORY.CREATED
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILE_IMPORT_HISTORY.CREATED
     *
     * @param created the value for T_FILE_IMPORT_HISTORY.CREATED
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILE_IMPORT_HISTORY.UPDATED
     *
     * @return the value of T_FILE_IMPORT_HISTORY.UPDATED
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILE_IMPORT_HISTORY.UPDATED
     *
     * @param updated the value for T_FILE_IMPORT_HISTORY.UPDATED
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}