package com.landasoft.excelcontactsorcl.pojo;

import java.util.Date;

public class TFileSheet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILE_SHEET.ID
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILE_SHEET.VALUE
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILE_SHEET.TITLE
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILE_SHEET.FILE_ID
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILE_SHEET.CREATED
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILE_SHEET.UPDATED
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILE_SHEET.ID
     *
     * @return the value of T_FILE_SHEET.ID
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILE_SHEET.ID
     *
     * @param id the value for T_FILE_SHEET.ID
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILE_SHEET.VALUE
     *
     * @return the value of T_FILE_SHEET.VALUE
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILE_SHEET.VALUE
     *
     * @param value the value for T_FILE_SHEET.VALUE
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILE_SHEET.TITLE
     *
     * @return the value of T_FILE_SHEET.TITLE
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILE_SHEET.TITLE
     *
     * @param title the value for T_FILE_SHEET.TITLE
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILE_SHEET.FILE_ID
     *
     * @return the value of T_FILE_SHEET.FILE_ID
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILE_SHEET.FILE_ID
     *
     * @param fileId the value for T_FILE_SHEET.FILE_ID
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILE_SHEET.CREATED
     *
     * @return the value of T_FILE_SHEET.CREATED
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILE_SHEET.CREATED
     *
     * @param created the value for T_FILE_SHEET.CREATED
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILE_SHEET.UPDATED
     *
     * @return the value of T_FILE_SHEET.UPDATED
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILE_SHEET.UPDATED
     *
     * @param updated the value for T_FILE_SHEET.UPDATED
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}