package com.landasoft.excelcontactsorcl.pojo;

public class TInterprise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE.ID
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE.EID
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    private String eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE.ENAME
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE.TAG
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    private Short tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE.CREATED_TIME
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE.CREATED
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    private String created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE.UPDATED
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    private String updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE.SAME_PERSON
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    private String samePerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE.ID
     *
     * @return the value of T_INTERPRISE.ID
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE.ID
     *
     * @param id the value for T_INTERPRISE.ID
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE.EID
     *
     * @return the value of T_INTERPRISE.EID
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE.EID
     *
     * @param eid the value for T_INTERPRISE.EID
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    public void setEid(String eid) {
        this.eid = eid == null ? null : eid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE.ENAME
     *
     * @return the value of T_INTERPRISE.ENAME
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE.ENAME
     *
     * @param ename the value for T_INTERPRISE.ENAME
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE.TAG
     *
     * @return the value of T_INTERPRISE.TAG
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    public Short getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE.TAG
     *
     * @param tag the value for T_INTERPRISE.TAG
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    public void setTag(Short tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE.CREATED_TIME
     *
     * @return the value of T_INTERPRISE.CREATED_TIME
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE.CREATED_TIME
     *
     * @param createdTime the value for T_INTERPRISE.CREATED_TIME
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE.CREATED
     *
     * @return the value of T_INTERPRISE.CREATED
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    public String getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE.CREATED
     *
     * @param created the value for T_INTERPRISE.CREATED
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    public void setCreated(String created) {
        this.created = created == null ? null : created.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE.UPDATED
     *
     * @return the value of T_INTERPRISE.UPDATED
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    public String getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE.UPDATED
     *
     * @param updated the value for T_INTERPRISE.UPDATED
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    public void setUpdated(String updated) {
        this.updated = updated == null ? null : updated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE.SAME_PERSON
     *
     * @return the value of T_INTERPRISE.SAME_PERSON
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    public String getSamePerson() {
        return samePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE.SAME_PERSON
     *
     * @param samePerson the value for T_INTERPRISE.SAME_PERSON
     *
     * @mbggenerated Fri May 29 11:07:35 CST 2020
     */
    public void setSamePerson(String samePerson) {
        this.samePerson = samePerson == null ? null : samePerson.trim();
    }
}