package com.landasoft.excelcontactsorcl.pojo;

import java.util.Date;

public class TInterpriseCtrl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE_CTRL.IDS
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE_CTRL.PEID
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    private String peid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE_CTRL.PNAME
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE_CTRL.CEID
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    private String ceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE_CTRL.CNAME
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE_CTRL.CONTENT
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE_CTRL.TYPES
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    private String types;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE_CTRL.CREATED
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE_CTRL.UPDATED
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE_CTRL.REMARK
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE_CTRL.CREATED_TIME
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INTERPRISE_CTRL.TAG
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    private Short tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE_CTRL.IDS
     *
     * @return the value of T_INTERPRISE_CTRL.IDS
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public String getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE_CTRL.IDS
     *
     * @param ids the value for T_INTERPRISE_CTRL.IDS
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE_CTRL.PEID
     *
     * @return the value of T_INTERPRISE_CTRL.PEID
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public String getPeid() {
        return peid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE_CTRL.PEID
     *
     * @param peid the value for T_INTERPRISE_CTRL.PEID
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public void setPeid(String peid) {
        this.peid = peid == null ? null : peid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE_CTRL.PNAME
     *
     * @return the value of T_INTERPRISE_CTRL.PNAME
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE_CTRL.PNAME
     *
     * @param pname the value for T_INTERPRISE_CTRL.PNAME
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE_CTRL.CEID
     *
     * @return the value of T_INTERPRISE_CTRL.CEID
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public String getCeid() {
        return ceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE_CTRL.CEID
     *
     * @param ceid the value for T_INTERPRISE_CTRL.CEID
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public void setCeid(String ceid) {
        this.ceid = ceid == null ? null : ceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE_CTRL.CNAME
     *
     * @return the value of T_INTERPRISE_CTRL.CNAME
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE_CTRL.CNAME
     *
     * @param cname the value for T_INTERPRISE_CTRL.CNAME
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE_CTRL.CONTENT
     *
     * @return the value of T_INTERPRISE_CTRL.CONTENT
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE_CTRL.CONTENT
     *
     * @param content the value for T_INTERPRISE_CTRL.CONTENT
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE_CTRL.TYPES
     *
     * @return the value of T_INTERPRISE_CTRL.TYPES
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public String getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE_CTRL.TYPES
     *
     * @param types the value for T_INTERPRISE_CTRL.TYPES
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public void setTypes(String types) {
        this.types = types == null ? null : types.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE_CTRL.CREATED
     *
     * @return the value of T_INTERPRISE_CTRL.CREATED
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE_CTRL.CREATED
     *
     * @param created the value for T_INTERPRISE_CTRL.CREATED
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE_CTRL.UPDATED
     *
     * @return the value of T_INTERPRISE_CTRL.UPDATED
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE_CTRL.UPDATED
     *
     * @param updated the value for T_INTERPRISE_CTRL.UPDATED
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE_CTRL.REMARK
     *
     * @return the value of T_INTERPRISE_CTRL.REMARK
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE_CTRL.REMARK
     *
     * @param remark the value for T_INTERPRISE_CTRL.REMARK
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE_CTRL.CREATED_TIME
     *
     * @return the value of T_INTERPRISE_CTRL.CREATED_TIME
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE_CTRL.CREATED_TIME
     *
     * @param createdTime the value for T_INTERPRISE_CTRL.CREATED_TIME
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INTERPRISE_CTRL.TAG
     *
     * @return the value of T_INTERPRISE_CTRL.TAG
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public Short getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INTERPRISE_CTRL.TAG
     *
     * @param tag the value for T_INTERPRISE_CTRL.TAG
     *
     * @mbggenerated Fri May 29 15:24:56 CST 2020
     */
    public void setTag(Short tag) {
        this.tag = tag;
    }
}