package com.landasoft.excelcontactsorcl.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TItemInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ITEM_INFO.ID
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ITEM_INFO.TITLE
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ITEM_INFO.SELL_POINT
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    private String sellPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ITEM_INFO.PRICE
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ITEM_INFO.NUM
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    private BigDecimal num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ITEM_INFO.BARCODE
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    private String barcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ITEM_INFO.IMAGE
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ITEM_INFO.CID
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ITEM_INFO.CNAME
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ITEM_INFO.STATUS
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ITEM_INFO.CREATED
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ITEM_INFO.UPDATED
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ITEM_INFO.IMPORT_NUM
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    private Short importNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ITEM_INFO.FILE_ID
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ITEM_INFO.DESCS
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    private String descs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ITEM_INFO.ID
     *
     * @return the value of T_ITEM_INFO.ID
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ITEM_INFO.ID
     *
     * @param id the value for T_ITEM_INFO.ID
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ITEM_INFO.TITLE
     *
     * @return the value of T_ITEM_INFO.TITLE
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ITEM_INFO.TITLE
     *
     * @param title the value for T_ITEM_INFO.TITLE
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ITEM_INFO.SELL_POINT
     *
     * @return the value of T_ITEM_INFO.SELL_POINT
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public String getSellPoint() {
        return sellPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ITEM_INFO.SELL_POINT
     *
     * @param sellPoint the value for T_ITEM_INFO.SELL_POINT
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public void setSellPoint(String sellPoint) {
        this.sellPoint = sellPoint == null ? null : sellPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ITEM_INFO.PRICE
     *
     * @return the value of T_ITEM_INFO.PRICE
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ITEM_INFO.PRICE
     *
     * @param price the value for T_ITEM_INFO.PRICE
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ITEM_INFO.NUM
     *
     * @return the value of T_ITEM_INFO.NUM
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public BigDecimal getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ITEM_INFO.NUM
     *
     * @param num the value for T_ITEM_INFO.NUM
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public void setNum(BigDecimal num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ITEM_INFO.BARCODE
     *
     * @return the value of T_ITEM_INFO.BARCODE
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ITEM_INFO.BARCODE
     *
     * @param barcode the value for T_ITEM_INFO.BARCODE
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ITEM_INFO.IMAGE
     *
     * @return the value of T_ITEM_INFO.IMAGE
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ITEM_INFO.IMAGE
     *
     * @param image the value for T_ITEM_INFO.IMAGE
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ITEM_INFO.CID
     *
     * @return the value of T_ITEM_INFO.CID
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ITEM_INFO.CID
     *
     * @param cid the value for T_ITEM_INFO.CID
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ITEM_INFO.CNAME
     *
     * @return the value of T_ITEM_INFO.CNAME
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ITEM_INFO.CNAME
     *
     * @param cname the value for T_ITEM_INFO.CNAME
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ITEM_INFO.STATUS
     *
     * @return the value of T_ITEM_INFO.STATUS
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ITEM_INFO.STATUS
     *
     * @param status the value for T_ITEM_INFO.STATUS
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ITEM_INFO.CREATED
     *
     * @return the value of T_ITEM_INFO.CREATED
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ITEM_INFO.CREATED
     *
     * @param created the value for T_ITEM_INFO.CREATED
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ITEM_INFO.UPDATED
     *
     * @return the value of T_ITEM_INFO.UPDATED
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ITEM_INFO.UPDATED
     *
     * @param updated the value for T_ITEM_INFO.UPDATED
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ITEM_INFO.IMPORT_NUM
     *
     * @return the value of T_ITEM_INFO.IMPORT_NUM
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public Short getImportNum() {
        return importNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ITEM_INFO.IMPORT_NUM
     *
     * @param importNum the value for T_ITEM_INFO.IMPORT_NUM
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public void setImportNum(Short importNum) {
        this.importNum = importNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ITEM_INFO.FILE_ID
     *
     * @return the value of T_ITEM_INFO.FILE_ID
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ITEM_INFO.FILE_ID
     *
     * @param fileId the value for T_ITEM_INFO.FILE_ID
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ITEM_INFO.DESCS
     *
     * @return the value of T_ITEM_INFO.DESCS
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ITEM_INFO.DESCS
     *
     * @param descs the value for T_ITEM_INFO.DESCS
     *
     * @mbggenerated Sun Jul 05 00:06:57 CST 2020
     */
    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }
}