package com.landasoft.excelcontactsorcl.mapper;

import com.landasoft.excelcontactsorcl.pojo.TFileSheet;
import com.landasoft.excelcontactsorcl.pojo.TFileSheetExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TFileSheetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_SHEET
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    int countByExample(TFileSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_SHEET
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    int deleteByExample(TFileSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_SHEET
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_SHEET
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    int insert(TFileSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_SHEET
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    int insertSelective(TFileSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_SHEET
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    List<TFileSheet> selectByExample(TFileSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_SHEET
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    TFileSheet selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_SHEET
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") TFileSheet record, @Param("example") TFileSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_SHEET
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    int updateByExample(@Param("record") TFileSheet record, @Param("example") TFileSheetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_SHEET
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    int updateByPrimaryKeySelective(TFileSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_SHEET
     *
     * @mbggenerated Tue May 26 09:53:50 CST 2020
     */
    int updateByPrimaryKey(TFileSheet record);
}