package com.landasoft.excelcontactsorcl.mapper;

import com.landasoft.excelcontactsorcl.pojo.TFileImportHistory;
import com.landasoft.excelcontactsorcl.pojo.TFileImportHistoryExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TFileImportHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_IMPORT_HISTORY
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    int countByExample(TFileImportHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_IMPORT_HISTORY
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    int deleteByExample(TFileImportHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_IMPORT_HISTORY
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_IMPORT_HISTORY
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    int insert(TFileImportHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_IMPORT_HISTORY
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    int insertSelective(TFileImportHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_IMPORT_HISTORY
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    List<TFileImportHistory> selectByExample(TFileImportHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_IMPORT_HISTORY
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    TFileImportHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_IMPORT_HISTORY
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") TFileImportHistory record, @Param("example") TFileImportHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_IMPORT_HISTORY
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    int updateByExample(@Param("record") TFileImportHistory record, @Param("example") TFileImportHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_IMPORT_HISTORY
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    int updateByPrimaryKeySelective(TFileImportHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE_IMPORT_HISTORY
     *
     * @mbggenerated Sun Jul 05 00:21:40 CST 2020
     */
    int updateByPrimaryKey(TFileImportHistory record);
}